---
- name: install and uninstall packages
  hosts: all
  become: true
  tasks:
   - name: install and uninstall
     apt:
       name: "{{item.a}}"
       state: "{{item.b}}"
       update_cache: "{{item.c}}"
     with_items:
      - {a: git, b: present, c: yes}
      - {a: maven, b: present, c: yes}
      - {a: default-jdk, b: present, c: yes}
      - {a: tree, b: absent, c: no}
      - {a: elinks, b: absent, c: no}
