---
- name: create a user and create a file in the user's workspace
  hosts: all
  become: true
  tasks:
    - name: create a user
      user:
        name: ramesh
        password: 123456
        home: /home/ramesh
        comment: developer
        uid: 1005
        shell: /bin/bash
    - name: create a file in user's workspace
      file:
        name: /home/ramesh/ramesh.txt
        state: touch
...
